name: Cloudflare DNS Updater

on:
  schedule:
    - cron: "* * * * *" # every minute (60 seconds)
  workflow_dispatch:

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run Cloudflare DNS updater
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
        run: php script.php
