name: Run DNS Update

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:     # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run PHP script
        run: php script.php
